#!/bin/sh
set -e

[[ -z "$TRACE" ]] || set -x

# --help, --version
[ "$1" = "--help" ] || [ "$1" = "--version" ] && exec pdns_server $1

# treat everything except -- as exec cmd
[ "${1:0:2}" != "--" ] && exec "$@"

SOURCE_ONLY=1 . pdns-script-helpers
pdnsExportKubeEtc ~/.pgenv.owner

pdns-preseed-etc
pdns-preseed-pg

# environment hygiene
for var in $(printenv | cut -f1 -d= | grep -v -e HOME -e USER -e PATH ); do unset $var; done
export TZ=UTC LANG=C LC_ALL=C

# create zones
for zone in $(echo "$PDNS_ZONES" | sed "s/,/ /g")
do
	echo zone $zone
	pdnsutil -v create-zone $zone
done

echo status: run
# run the server
exec pdns_server "$@"
