#!/bin/sh

pdnsHealthcheckApi(){
	if ! command -v pdnsCurl
	then
		SOURCE_ONLY=1 . pdns-curl
	fi

	pdnsCurl '/api/v1/servers/localhost'
	return $?
}

if [ -z "$SOURCE_ONLY" ]
then
	pdnsHealthcheckApi $*
	return $?
fi
