#!/bin/sh
set -e

[[ -z "$TRACE" ]] || set -x

# --help, --version
[ "$1" = "--help" ] || [ "$1" = "--version" ] && exec pdns_server $1

# treat everything except -- as exec cmd
[ "${1:0:2}" != "--" ] && exec "$@"

echo status: files
find /etc/powerdns

echo status: healthcheck
pdns-healthcheck-pg

echo status: preseed-etc
pdns-preseed-etc &
echo status: preseed-pg
pdns-preseed-pg &

wait

# environment hygiene
for var in $(printenv | cut -f1 -d= | grep -v -e HOME -e USER -e PATH ); do unset $var; done
export TZ=UTC LANG=C LC_ALL=C

echo status: env
env

# create zones
for zone in $(echo "$PDNS_ZONES" | sed "s/,/ /g")
do
	echo zone $zone
	pdnsutil -v create-zone $zone
done

echo status: run
# run the server
exec pdns_server "$@"
