#!/bin/sh

pdnsHealthcheckPg(){
	local sec="${1:-${PDNS_HEALTHCHECK_TIMEOUT:-60}}"

	if [ -z "$PGUSER" ]
	then
		echo "no PGUSER for healthcheck" 1>&2
		return 1
	fi

	while [ "$sec" -gt 0 ]
	do
		echo "SELECT 1" | pdns-psql >/dev/null
		if [ $? -eq 0 ]
		then
			return 0
		fi
		sleep 5
		sec="$((sec - 5))"
	done
	echo "database did not respond" 1>&2
	return 1
}

if [ -z "$SOURCE_ONLY" ]
then
	 pdnsHealthcheckPg $*
fi
