#!/bin/sh

pdnsCurl(){
	local path=${1##/}
	shift

	local WEBSERVER_PORT="$(cat /etc/powerdns/kube/*/webserver-port | tail -n1)"
	local WEBSERVER_API_KEY="$(cat /etc/powerdns/kube/*/api-key | tail -n1)"
	curl --fail -s -H "X-API-Key: $WEBSERVER_API_KEY" http://localhost:$WEBSERVER_PORT/$path $*
	return $?
}


if [ -z "SOURCE_ONLY" ]
then
	pdnsCurl $*
fi
