#!/bin/sh

set -e
set -x

getEnv(){
	local confs="$(grep -h gpgsql /etc/powerdns/pdns.conf $PDNS_CONFD_DIR/*conf 2>/dev/null)"

	printf "%s\n" "$confs" | while IFS= read -r line
	do
		echo line $line
	done 
}

getEnv
