#!/bin/sh

# use pdns-kube-etc to read kube config dirs, writing /etc/powerdns/conf.d files
pdnsPreseedEtc(){
	local dir="${1:-${PDNS_KUBE_ETC_DIRS:-/etc/powerdns/kube}}"
	local confd="${PDNS_CONFD_DIR:-/etc/powerdns/conf.d}"

	for entry in $dir/*
	do
		local key="$(basename $entry)"
		pdns-kube-etc "$entry" > "$confd/$key.conf"
	done
}

if [ -z "$SOURCE_ONLY" ]
then
	echo pre preseed etc 1>&2
	pdnsPreseedEtc $*
fi
